name: vendr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  another_flushbar: 1.12.31-dev.1
  # cached_network_image: 3.4.1
  # cloud_firestore: ^6.0.1
  envied: 1.1.1
  file_picker: 10.2.0
  # firebase_auth: ^6.0.2
  # firebase_core: ^4.1.0
  # firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_gen: 5.10.0
  # flutter_google_places_sdk: 0.4.2+1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: 4.0.1
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.4
  flutter_svg: 2.1.0
  http: 1.4.0
  http_parser: 4.1.2
  percent_indicator: 4.2.5
  # image_picker: 1.1.2
  intl: 0.20.2
  json_annotation: 4.9.0
  keyboard_actions: 4.2.0
  # mime: 2.0.0
  path: 1.9.1
  pinput: 5.0.1
  provider: 6.1.5
  # shimmer: 3.0.0
  url_launcher: 6.3.2
  # google_maps_flutter: ^2.13.1
  # geolocator: ^14.0.2

dev_dependencies:
  build_runner: 2.5.4
  envied_generator: 1.1.1
  flutter_gen_runner: 5.10.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  json_serializable: 6.9.5
  very_good_analysis: 9.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/blocks_pattern.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway/static/Raleway-Thin.ttf
            weight: 100
          - asset: assets/fonts/Raleway/static/Raleway-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Raleway/static/Raleway-ExtraLightItalic.ttf
            weight: 200
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-Light.ttf
            weight: 300
          - asset: assets/fonts/Raleway/static/Raleway-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-Regular.ttf
            weight: 400
          - asset: assets/fonts/Raleway/static/Raleway-Italic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-Medium.ttf
            weight: 500
          - asset: assets/fonts/Raleway/static/Raleway-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Raleway/static/Raleway-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-Bold.ttf
            weight: 700
          - asset: assets/fonts/Raleway/static/Raleway-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          - asset: assets/fonts/Raleway/static/Raleway-Black.ttf
            weight: 900
          - asset: assets/fonts/Raleway/static/Raleway-BlackItalic.ttf
            weight: 900
            style: italic

flutter_gen:
  output: lib/generated/assets
  integrations:
    flutter_svg: true